In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

In [2]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
from ECOv002_calval_tables import load_calval_table
from FLiESANN import load_ECOv002_calval_FLiESANN_outputs
from BESS_JPL import load_ECOv002_static_tower_BESS_inputs
from BESS_JPL import process_BESS_table

[2025-11-21 09:21:22 INFO] SRTM working directory: ~/data/NASADEM
[2025-11-21 09:21:22 INFO] SRTM download directory: ~/data/NASADEM

In [3]:
repo_root = os.path.dirname(os.getcwd())
package_dir = os.path.join(repo_root, 'BESS_JPL')
generated_input_table_filename = os.path.join(package_dir, "ECOv002-cal-val-BESS-JPL-inputs.csv")
generated_output_table_filename = os.path.join(package_dir, "ECOv002-cal-val-BESS-JPL-outputs.csv")

In [4]:
# model_inputs_gdf = load_calval_table()
model_inputs_gdf = load_ECOv002_calval_FLiESANN_outputs()
model_inputs_gdf["elevation_km"] = model_inputs_gdf["Elev"] / 1000.0
model_inputs_gdf.head()

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,NIR_diffuse_fraction,SWin_TOA_Wm2,UV_Wm2,PAR_Wm2,NIR_Wm2,PAR_diffuse_Wm2,NIR_diffuse_Wm2,PAR_direct_Wm2,NIR_direct_Wm2,elevation_km
0,0,US-NC3,ENF,Cfa,270.34520,78.53355,392.85184,307.02197,487.383423,118.91628,...,0.126794,884.3206,37.197750,297.09644,301.62590,98.470250,38.244500,198.62619,263.38138,0.005
1,1,US-Mi3,CVM,Dfb,232.14160,229.20093,640.11847,375.08930,106.825577,167.91946,...,0.000000,1199.2876,61.882423,448.33093,504.05743,34.749706,0.000000,413.58124,504.05743,0.270
2,2,US-Mi3,CVM,Dfb,356.35574,335.23154,625.66170,284.68625,NaN,132.93634,...,0.020261,1205.0444,59.888542,445.19970,478.15155,60.458492,9.687667,384.74120,468.46390,0.270
3,3,US-Mi3,CVM,Dfb,332.93840,326.68680,624.25433,251.41449,178.827545,141.13242,...,0.004152,1142.2208,57.067180,418.59454,464.95883,34.440212,1.930551,384.15433,463.02830,0.270
4,4,US-Mi3,CVM,Dfb,286.85403,237.21654,511.08218,228.52017,154.791626,114.80941,...,0.036793,1042.2742,49.484960,368.71317,398.33896,46.295307,14.656249,322.41785,383.68270,0.270

In [5]:
static_inputs_df = load_ECOv002_static_tower_BESS_inputs()
static_inputs_df

,ID,name,NDVI_minimum,NDVI_maximum,C4_fraction,carbon_uptake_efficiency,kn,peakVCmax_C3,peakVCmax_C4,ball_berry_slope_C3,...,KG_climate,CI,canopy_height_meters,COT,AOT,Ca,wind_speed_mps,vapor_gccm,ozone_cm,geometry
0,US-NC3,NC_Clearcut#3,0.408733,0.855693,0.077532,0.080000,0.410000,87.345433,51.040624,9.5,...,3,0.282353,20.642902,0,0,400,0,0,0.3,POINT (-76.656 35.799)
1,PE-QFR,Quistococha Forest Reserve,0.657359,0.826605,0.000549,0.060347,0.125033,41.364487,41.364487,9.5,...,1,0.254902,22.140021,0,0,400,0,0,0.3,POINT (-73.319 -3.8344)
2,US-Mi3,LTAR UCB (Upper Chesapeake Bay) Miscanthus 3,0.027910,0.855461,0.035045,0.080000,0.410000,119.435443,119.435443,7.5,...,4,0.286275,0.000000,0,0,400,0,0,0.3,POINT (-80.637 41.8222)
3,US-NC4,NC_AlligatorRiver,0.591358,0.869758,0.046219,0.080000,0.410000,64.720165,64.720165,9.5,...,3,0.207843,14.164827,0,0,400,0,0,0.3,POINT (-75.9038 35.7879)
4,CA-DB2,Delta Burns Bog 2,0.399712,0.675731,0.000356,0.080000,0.410000,109.986395,109.986395,9.5,...,3,0.266667,9.919029,0,0,400,0,0,0.3,POINT (-122.9951 49.119)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,US-xSL,"NEON North Sterling, CO (STER)",-0.025449,0.495206,0.340776,0.090000,0.710000,78.000000,40.000000,9.5,...,2,0.298039,0.000000,0,0,400,0,0,0.3,POINT (-103.0293 40.4619)
117,US-xWD,NEON Woodworth (WOOD),-0.041785,0.753863,0.032479,0.080000,0.410000,101.000000,37.000000,7.5,...,4,0.294118,0.000000,0,0,400,0,0,0.3,POINT (-99.2414 47.1282)
118,US-CS4,Central Sands Irrigated Agricultural Field,-0.003026,0.776740,0.092454,0.080000,0.410000,101.000000,37.000000,7.5,...,4,0.278431,0.000000,0,0,400,0,0,0.3,POINT (-89.5475 44.1597)
119,US-xAE,NEON Klemme Range Research Station (OAES),0.233503,0.554538,0.371127,0.090000,0.710000,78.000000,40.000000,9.5,...,3,0.301961,0.000000,0,0,400,0,0,0.3,POINT (-99.0588 35.4106)
120,US-GLE,GLEES,0.083431,0.708367,0.001423,0.088097,0.652918,137.813997,55.221827,7.5,...,4,0.200000,15.028475,0,0,400,0,0,0.3,POINT (-106.2399 41.3665)

In [6]:
# merge static inputs with model inputs, ignoring duplicate columns from static_inputs_df
cols_to_use = [col for col in static_inputs_df.columns if col not in model_inputs_gdf.columns or col == 'ID']
model_inputs_gdf = model_inputs_gdf.merge(static_inputs_df[cols_to_use], on="ID", how="left")
model_inputs_gdf

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,kn,peakVCmax_C3,peakVCmax_C4,ball_berry_slope_C3,ball_berry_slope_C4,ball_berry_intercept_C3,CI,canopy_height_meters,Ca,wind_speed_mps
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,0.41,87.345433,51.040624,9.5,4.951963,0.005267,0.282353,20.642902,400,0
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,0.41,119.435443,119.435443,7.5,4.121171,0.009882,0.286275,0.000000,400,0
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,0.41,119.435443,119.435443,7.5,4.121171,0.009882,0.286275,0.000000,400,0
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,0.41,119.435443,119.435443,7.5,4.121171,0.009882,0.286275,0.000000,400,0
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,0.41,119.435443,119.435443,7.5,4.121171,0.009882,0.286275,0.000000,400,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,0.71,78.000000,40.000000,9.5,5.800000,0.015000,0.301961,0.000000,400,0
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,0.71,78.000000,40.000000,9.5,5.800000,0.015000,0.301961,0.000000,400,0
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,0.71,78.000000,40.000000,9.5,5.800000,0.015000,0.301961,0.000000,400,0
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,0.71,78.000000,40.000000,9.5,5.800000,0.015000,0.301961,0.000000,400,0
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,0.71,78.000000,40.000000,9.5,5.800000,0.015000,0.301961,0.000000,400,0

In [7]:
model_inputs_gdf.columns

Index(['Unnamed: 0', 'ID', 'vegetation', 'climate', 'STICinst', 'BESSinst',
       'MOD16inst', 'PTJPLSMinst', 'ETinst', 'ETinstUncertainty',
       ...
       'kn', 'peakVCmax_C3', 'peakVCmax_C4', 'ball_berry_slope_C3',
       'ball_berry_slope_C4', 'ball_berry_intercept_C3', 'CI',
       'canopy_height_meters', 'Ca', 'wind_speed_mps'],
      dtype='object', length=124)

In [8]:
results = process_BESS_table(model_inputs_gdf)
results

[2025-11-21 09:21:22 INFO] started extracting geometry from PT-JPL-SM input table
[2025-11-21 09:21:22 INFO] completed extracting geometry from PT-JPL-SM input table
[2025-11-21 09:21:22 INFO] started extracting time from PT-JPL-SM input table
[2025-11-21 09:21:22 INFO] completed extracting time from PT-JPL-SM input table
[2025-11-21 09:21:22 INFO] variable elevation_m min: 1.000 mean: 992.883 max: 3504.000 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Ta_C min: -14.605 mean: 22.322 max: 39.710 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable RH min: 0.273 mean: 0.427 max: 0.984 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable NDVI_minimum min: -0.033 mean: 0.174 max: 0.591 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable NDVI_maximum min: 0.314 mean: 0.628 max: 0.918 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable C4_fraction min: 0.000 mean: 0.296 max: 0.939 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable carbon_uptake_efficiency min: 0.080 mean: 0.083 max: 0.090 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable kn min: 0.410 mean: 0.514 max: 0.710 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable peakVCmax_C3 min: 52.821 mean: 88.903 max: 140.723 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable peakVCmax_C4 min: 37.000 mean: 65.191 max: 120.000 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable ball_berry_slope_C3 min: 7.500 mean: 8.698 max: 9.500 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable ball_berry_slope_C4 min: 4.100 mean: 5.177 max: 5.800 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable ball_berry_intercept_C3 min: 0.005 mean: 0.009 max: 0.015 nan: 0.00% (nan)
[2025-11-21 09:21:22 WARNING] Variable 'SWin_Wm2' is None.
[2025-11-21 09:21:22 WARNING] Variable 'PAR_diffuse_Wm2' is None.
[2025-11-21 09:21:22 WARNING] Variable 'PAR_direct_Wm2' is None.
[2025-11-21 09:21:22 WARNING] Variable 'NI_diffuse_Wm2' is None.
[2025-11-21 09:21:22 WARNING] Variable 'NI_direct_Wm2' is None.
[2025-11-21 09:21:22 WARNING] Variable 'UV_Wm2' is None.
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step
[2025-11-21 09:21:22 INFO] variable PAR_direct_Wm2 min: 61.502 mean: 281.634 max: 473.257 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable KG_climate (float32) with [1. 2. 3. 4. 5.] unique values
[2025-11-21 09:21:22 INFO] * 1.0: 3
[2025-11-21 09:21:22 INFO] * 2.0: 473
[2025-11-21 09:21:22 INFO] * 3.0: 172
[2025-11-21 09:21:22 INFO] * 4.0: 413
[2025-11-21 09:21:22 INFO] * 5.0: 4
[2025-11-21 09:21:22 INFO] variable canopy_height_meters min: 0.000 mean: 6.044 max: 30.192 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Ca (float64) with [400.] unique values
[2025-11-21 09:21:22 INFO] * 400.0: 1065
[2025-11-21 09:21:22 INFO] variable wind_speed_mps (float64) with [7.4] unique values
[2025-11-21 09:21:22 INFO] * 7.4: 1065
[2025-11-21 09:21:22 INFO] variable Ps_Pa min: 64923.167 mean: 90420.237 max: 101313.196 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable VPD_Pa min: 9.430 mean: 1742.970 max: 4717.745 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable RH min: 0.273 mean: 0.426 max: 0.985 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable desTa min: 16.249 mean: 176.854 max: 387.676 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable ddesTa min: 1.197 mean: 9.169 max: 17.906 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable gamma min: 42.603 mean: 60.201 max: 68.164 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Cp min: 1005.693 mean: 1012.855 max: 1022.895 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable rhoa min: 0.776 mean: 1.067 max: 1.314 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable epsa min: 0.658 mean: 0.770 max: 0.879 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable R min: 6.213 mean: 24.217 max: 32.659 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rc min: 6.213 mean: 24.217 max: 32.659 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rs min: 3.107 mean: 12.109 max: 16.330 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable SFd min: 0.020 mean: 0.051 max: 0.083 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable SFd2 min: 0.157 mean: 0.331 max: 1.126 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable DL min: 7.316 mean: 11.455 max: 14.086 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Ra min: 409.312 mean: 901.634 max: 1276.344 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable fStress min: 0.007 mean: 0.295 max: 1.000 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable VCmax_C3_sunlit_μmolm2s1 min: 1.804 mean: 39.242 max: 159.939 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable VCmax_C4_sunlit_μmolm2s1 min: 1.438 mean: 30.612 max: 148.721 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable VCmax_C3_shaded_μmolm2s1 min: 0.060 mean: 36.813 max: 264.371 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable VCmax_C4_shaded_μmolm2s1 min: 0.060 mean: 31.494 max: 264.371 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable PARDiff min: 18.773 mean: 40.476 max: 158.456 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable PARDir min: 61.502 mean: 281.634 max: 473.257 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable NIRDiff min: 0.000 mean: 8.460 max: 95.964 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable NIRDir min: 118.387 mean: 361.622 max: 591.598 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable UV min: 14.174 mean: 43.023 max: 76.912 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable SZA min: 8.815 mean: 44.939 max: 72.288 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable LAI min: 0.076 mean: 1.285 max: 4.516 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable CI min: 0.184 mean: 0.278 max: 1.000 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable albedo_visible min: 0.015 mean: 0.109 max: 0.617 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable albedo_NIR min: 0.015 mean: 0.109 max: 0.617 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable kb min: 0.506 mean: 0.787 max: 1.643 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable kk_Pb min: 0.465 mean: 0.724 max: 1.512 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable kk_Nb min: 0.212 mean: 0.329 max: 0.688 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable kk_Nd (float64) with [0.1464155] unique values
[2025-11-21 09:21:22 INFO] * 0.14641550464346323: 1
[2025-11-21 09:21:22 INFO] variable fSun min: 0.118 mean: 0.240 max: 0.580 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable L_CI min: 0.021 mean: 0.374 max: 3.967 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable exp_kk_Pd_L_CI min: 0.057 mean: 0.795 max: 0.985 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable exp_kk_Nd_L_CI min: 0.559 mean: 0.949 max: 0.997 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARin_Wm2 min: 3.264 mean: 55.276 max: 332.524 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARin_sunlit_Wm2 min: 3.376 mean: 46.379 max: 287.946 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARin_diffuse_Wm2 min: 0.446 mean: 6.579 max: 51.446 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARin_scattered_sunlit_Wm2 min: 0.000 mean: 1.189 max: 14.212 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARin_sunlit_Wm2 min: 3.822 mean: 54.148 max: 309.423 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARin_shade_Wm2 min: 0.000 mean: 1.723 max: 43.266 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable PARin_soil_Wm2 min: 7.669 mean: 231.280 max: 414.664 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_Soil min: 6.519 mean: 196.588 max: 352.464 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARout_sunlit_Wm2 min: 0.066 mean: 28.704 max: 59.711 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APARout_shade_Wm2 min: 0.416 mean: 5.988 max: 20.846 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_sunlit_Wm2 min: 23.572 mean: 82.852 max: 309.909 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_shade_Wm2 min: 0.416 mean: 7.710 max: 47.351 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIRin_sunlit_Wm2 min: 1.736 mean: 27.229 max: 151.056 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIRin_shade_Wm2 min: 0.007 mean: 4.200 max: 99.812 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable NIRin_soil_Wm2 min: 50.246 mean: 298.587 max: 510.164 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIR_soil_Wm2 min: 35.172 mean: 209.011 max: 357.115 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIRout_sunlit_Wm2 min: 8.433 mean: 85.578 max: 149.312 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIRout_Wm2 min: 0.199 mean: 3.999 max: 22.706 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIR_sunlit_Wm2 min: 44.349 mean: 112.807 max: 183.531 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ANIR_shade_Wm2 min: 0.207 mean: 8.198 max: 121.033 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable G_Wm2 min: 1.825 mean: 55.045 max: 98.690 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ASW_sunlit_Wm2 min: 72.853 mean: 196.165 max: 493.800 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ASW_shade_Wm2 min: 0.743 mean: 17.590 max: 156.167 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ASW_soil_Wm2 min: 52.944 mean: 444.304 max: 771.476 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_sunlit_Wm2 min: 23.572 mean: 82.852 max: 309.909 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_sunlit_μmolm2s1 min: 107.490 mean: 377.805 max: 1413.185 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_shade_Wm2 min: 0.416 mean: 7.710 max: 47.351 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_shade_μmolm2s1 min: 1.896 mean: 35.159 max: 215.922 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable fSun min: 0.118 mean: 0.240 max: 0.580 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_sunlit_μmolm2s1 min: 107.490 mean: 377.805 max: 1413.185 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable APAR_shade_μmolm2s1 min: 1.896 mean: 35.159 max: 215.922 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ASW_sunlit_Wm2 min: 72.853 mean: 196.165 max: 493.800 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ASW_shade_Wm2 min: 0.743 mean: 17.590 max: 156.167 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable ASW_soil_Wm2 min: 52.944 mean: 444.304 max: 771.476 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable G_Wm2 min: 1.825 mean: 55.045 max: 98.690 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable GPP_C3 min: 0.000 mean: 8.883 max: 40.000 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable LE_C3 min: 0.000 mean: 112.222 max: 422.680 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable LE_soil_C3 min: 0.000 mean: 54.025 max: 240.711 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable LE_canopy_C3 min: 0.000 mean: 58.197 max: 378.410 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rn_C3 min: 0.000 mean: 468.927 max: 995.484 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rn_soil_C3 min: 0.000 mean: 350.357 max: 672.969 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rn_canopy_C3 min: 0.000 mean: 118.569 max: 547.004 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable GPP_C4 min: 0.000 mean: 13.015 max: 50.000 nan: 0.19% (nan)
[2025-11-21 09:21:22 INFO] variable LE_C4 min: 0.000 mean: 113.897 max: 479.899 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable LE_soil_C4 min: 0.000 mean: 54.025 max: 240.711 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable LE_canopy_C4 min: 0.000 mean: 59.872 max: 435.629 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rn_C4 min: 0.000 mean: 468.927 max: 995.484 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rn_soil_C4 min: 0.000 mean: 350.357 max: 672.969 nan: 0.00% (nan)
[2025-11-21 09:21:22 INFO] variable Rn_canopy_C4 min: 0.000 mean: 118.569 max: 547.004 nan: 0.00% (nan)

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,wind_speed_mps,GPP,GPP_daily,Rn_Wm2,Rn_soil_Wm2,Rn_canopy_Wm2,LE_Wm2,LE_soil_Wm2,LE_canopy_Wm2,G_Wm2
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,0,15.616766,5.711566,466.357577,297.381272,168.976305,226.980840,59.270467,167.710372,35.791947
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,0,21.021739,8.598512,709.085679,543.104519,165.981159,217.594847,95.668201,121.926646,74.268917
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,0,19.975842,8.116796,725.946606,543.887475,182.059132,320.113905,191.189198,128.924708,74.709546
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,0,24.097524,10.306391,694.866890,512.976422,181.890468,320.744921,195.970016,124.774905,68.422568
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,0,21.499935,10.067692,547.270243,407.281997,139.988246,240.925989,128.088996,112.836993,55.898896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,0,0.492825,0.193133,231.107920,163.076093,68.031827,45.934286,40.764830,5.169456,29.014390
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,0,1.258465,0.881543,247.155614,177.971270,69.184344,40.497186,28.962675,11.534511,31.763235
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,0,3.354856,2.400564,386.798873,254.162932,132.635940,46.527408,5.927288,40.600120,34.809273
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,0,1.985566,1.197199,295.591819,234.818866,60.772954,56.054382,46.078914,9.975468,43.789133
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,0,0.879118,0.323984,579.008150,480.598521,98.409628,38.310939,24.489348,13.821591,81.996860

In [9]:
model_inputs_gdf.to_csv(generated_input_table_filename, index=False)

In [10]:
results.to_csv(generated_output_table_filename, index=False)

In [11]:
for key, value in results.items():
    try:
        print(f"{key}: {np.nanmin(value)} {np.nanmean(value)} {np.nanmax(value)}")
    except:
        continue

Unnamed: 0: 0 532.0 1064
STICinst: 0.0 163.1636612074366 523.0476
BESSinst: 0.0 213.8509916843192 1000.0
MOD16inst: 0.0 294.62475544413144 762.08057
PTJPLSMinst: 0.0 171.57670828262908 526.5678
ETinst: 0.0 162.73812873411688 741.0538940429688
ETinstUncertainty: 0.0 123.6068336347418 420.74088
PET: 0.0 297.61518383230043 695.64197
Rn: 0.0 414.2791522507042 763.1359
ESI: 0.0 0.5617755694967136 1.0
RH: 0.27253073 0.42692000418779347 0.98366296
Ta: -14.605048 22.321587967441317 39.710495
LST: 258.72 302.1800469295775 359.26
SM: 0.0 0.16790158060469482 0.89711
NDVI: -0.02429185 0.4528892517239436 0.94546
NDVI-UQ: 0.00053067924 0.009029797618441315 0.09791492
albedo: 0.015407953 0.10903688726384977 0.6173986
albedo-UQ: 0.00057431095 0.006081434030807512 0.0493286
LST_err: 0.52 1.1144413145539904 2.96
view_zenith: 0.5024103 15.425197045624413 29.96069
Rg: -23.763361 606.9121518676056 1042.9371
EmisWB: 0.734 0.9682704225821597 0.984
solar_hour: 6.0 11.597183098591549 17.0
LE: -28.40977018 106.3085980362571 531.281873
LE_filt: -28.40977018 106.3085980362571 531.281873
LEcorr25: -33.13760618573642 122.32316631428814 641.6687449727063
LEcorr50: -38.85411052282232 157.3024068891697 784.7526465608905
LEcorr75: -17.031253610953804 146.7429644604656 752.8782772208383
LEcorr_ann: -39.10767467271954 150.1437904499561 745.5484807505868
H_filt: -28.658171414347 202.7764861164803 531.2852384
Hcorr25: -57.02196182691309 230.5108601717074 664.7400701846169
Hcorr50: -43.304482264901125 292.93395201864604 817.6991685168134
Hcorr75: -66.84312805133395 422.88039044406713 2039.495951298598
Hcorr_ann: -42.0130861627511 281.8846382552484 745.5532034203871
NETRAD_filt: 64.283 457.6603408529264 836.4
G_filt: -77.44275987 47.11332569813675 238.2108794
SM_surf: -0.013 0.14028110269294963 0.782
SM_rz: 0.00815 0.16684396521689135 0.782
AirTempC: -13.1333 21.41154206629282 39.56956666666667
SW_IN: 91.0037 709.3560643806478 1184.0
RH_percentage: 0.0267099999999999 0.3085610767383098 1.0
ESIrn_STIC: 0.0023815089461303 0.40438466031063075 1.0977622441831223
ESIrn_PTJPLSM: 0.0335418144399889 0.39770214662352227 0.8002859431720525
ESIrn_MOD16: 0.1760401639219172 0.6916719835442734 1.0
ESIrn_BESS: 0.0 0.6096405115753742 4.890706641624915
ESIrn_Unc_ECO: 0.047082439746417 0.32074410169859696 1.97785999230651
ESIrn_LEcorr50: -0.0800620451737529 0.3413816082947723 1.98955169286398
JET: 0.0 188.73857329887323 560.48651
Lat: 17.9696 37.57139220657277 46.242
Long: -122.3303 -103.53812037558686 -66.8687
Elev: 1.0 992.8825352112675 3504.0
MAT: -2.2 12.497699530516432 25.0
MAP: 271.33 703.8130610328639 2450.59
LE_count: 1716 50454.10892018779 80919
closure_ratio: 0.6 0.6988544600938968 1.02
elevation_m: 1.0 992.8825352112675 3504.0
ST_K: 258.72 302.1800469295775 359.26
ST_C: -14.42999999999995 29.030046929577487 86.11000000000001
Ta_C: -14.605048 22.321587967441317 39.710495
SWin_Wm2: 290.40512 733.899099774648 1153.1854
emissivity: 0.734 0.9682704225821597 0.984
insitu_LE_Wm2: -38.85411052282232 157.3024068891697 784.7526465608905
insitu_H_Wm2: -43.304482264901125 292.93395201864604 817.6991685168134
insitu_Rn_Wm2: 64.283 457.6603408529264 836.4
insitu_G_Wm2: -77.44275987 47.11332569813675 238.2108794
insitu_SWin_Wm2: 91.0037 709.3560643806478 1184.0
insitu_Rn_daylight_Wm2: 53.108950273507794 278.5401292813414 517.208995821767
insitu_LE_daylight_Wm2: -35.526838235162685 105.62850940647672 464.77368219778936
insitu_ET_daylight_kg: 0.0 2.1236081977715524 9.869530393200908
SZA_deg: 8.814830249922265 44.93929001859981 72.28756508074173
KG_climate: 1 2.9455399061032863 5
COT: 0.0 0.0 0.0
AOT: 0.0181834347682377 0.09381634934848616 0.8182031516403586
vapor_gccm: 0.1463432004450582 1.2559653376478823 5.110332885162654
ozone_cm: 0.2320347610883309 0.3031931132045357 0.4834927630586452
atmospheric_transmittance: 0.5775031 0.8065570739248826 0.90381944
UV_proportion: 0.046350885 0.05784131646103287 0.06753707
PAR_proportion: 0.40944922 0.4393802375117371 0.46748313
NIR_proportion: 0.47348213 0.504564982028169 0.5448811
UV_diffuse_fraction: 0.2571205 0.42906265895774653 0.8769748
PAR_diffuse_fraction: 0.03985522 0.13513346034647886 0.61633843
NIR_diffuse_fraction: 0.0 0.027124465421931455 0.32388785
SWin_TOA_Wm2: 409.31143 901.634022112676 1276.3439
UV_Wm2: 14.173724 43.022912536619714 76.911705
PAR_Wm2: 131.44737 322.11000251643196 496.1454
NIR_Wm2: 144.57895 370.0817076995305 591.59753
PAR_diffuse_Wm2: 18.773153 40.47641954460094 158.45566
NIR_diffuse_Wm2: 0.0 8.460010384854462 95.96412
PAR_direct_Wm2: 61.502007 281.6335827596244 473.25742
NIR_direct_Wm2: 118.386826 361.6216973014084 591.59753
elevation_km: 0.001 0.9928825352112679 3.504
NDVI_minimum: -0.0334048999845284 0.17403095904958787 0.5913575693840132
NDVI_maximum: 0.31389221495434 0.6283483895883738 0.9175582590433607
C4_fraction: 0.0 0.2957737615956438 0.9392833171850932
carbon_uptake_efficiency: 0.0799999982118606 0.08345209367596293 0.0900000035762787
kn: 0.4099999964237212 0.5135627986185466 0.7099999785423279
peakVCmax_C3: 52.82109356256992 88.90305481209344 140.72279481893938
peakVCmax_C4: 36.99999999999999 65.19099407851947 120.00000000000004
ball_berry_slope_C3: 7.499999999999998 8.698230389227481 9.500000000000004
ball_berry_slope_C4: 4.099999904632568 5.176822162760227 5.800000190734864
ball_berry_intercept_C3: 0.0049999998882412 0.00900401219731411 0.0149999996647238
CI: 0.1843137254901961 0.2783835036361962 1.0
canopy_height_meters: 0.0 6.0437079474051165 30.192381364266236
Ca: 400 400.0 400
wind_speed_mps: 0 0.0 0
GPP: 0.00013550176518813275 9.62502568692261 42.36180846140111
GPP_daily: 5.001005519126344e-05 4.4908520779634955 19.778304279520782
Rn_Wm2: 0.0 468.9269283082159 995.4835690787243
Rn_soil_Wm2: 0.0 350.35748876724773 672.9686210682573
Rn_canopy_Wm2: 0.0 118.56943954096813 547.0040703855253
LE_Wm2: 0.0 113.16212787825745 423.11708621534285
LE_soil_Wm2: 0.0 54.02488891060555 240.71120538727337
LE_canopy_Wm2: 0.0 59.13723896765191 378.8471480341923
G_Wm2: 1.8252055619789525 55.044702324188144 98.68992560081425