In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

In [2]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
from ECOv002_calval_tables import load_calval_table
from BESS_JPL import load_ECOv002_static_tower_BESS_inputs
from BESS_JPL import process_BESS_table

In [3]:
repo_root = os.path.dirname(os.getcwd())
package_dir = os.path.join(repo_root, 'BESS_JPL')
generated_input_table_filename = os.path.join(package_dir, "ECOv002-cal-val-BESS-JPL-inputs.csv")
generated_output_table_filename = os.path.join(package_dir, "ECOv002-cal-val-BESS-JPL-outputs.csv")

In [4]:
model_inputs_gdf = load_calval_table()
model_inputs_gdf["elevation_km"] = model_inputs_gdf["Elev"] / 1000.0
model_inputs_gdf.head()

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,LE_count,closure_ratio,geometry,time_UTC,ST_K,ST_C,Ta_C,SWin_Wm2,emissivity,elevation_km
0,0,US-NC3,ENF,Cfa,270.34520,78.53355,392.85184,307.02197,487.383423,118.91628,...,9576,1.02,POINT (-76.656 35.799),2019-10-02 19:09:40,305.10,31.95,32.658920,545.51056,0.948,0.005
1,1,US-Mi3,CVM,Dfb,232.14160,229.20093,640.11847,375.08930,106.825577,167.91946,...,12170,0.92,POINT (-80.637 41.8222),2019-06-23 18:17:17,304.34,31.19,24.227982,848.34390,0.952,0.270
2,2,US-Mi3,CVM,Dfb,356.35574,335.23154,625.66170,284.68625,NaN,132.93634,...,12170,0.92,POINT (-80.637 41.8222),2019-06-27 16:35:42,304.06,30.91,26.178862,838.81160,0.972,0.270
3,3,US-Mi3,CVM,Dfb,332.93840,326.68680,624.25433,251.41449,178.827545,141.13242,...,12170,0.92,POINT (-80.637 41.8222),2019-06-30 15:44:10,301.80,28.65,22.527096,851.72480,0.974,0.270
4,4,US-Mi3,CVM,Dfb,286.85403,237.21654,511.08218,228.52017,154.791626,114.80941,...,12170,0.92,POINT (-80.637 41.8222),2019-07-01 14:53:48,303.18,30.03,23.280691,702.55160,0.960,0.270

In [5]:
static_inputs_df = load_ECOv002_static_tower_BESS_inputs()
static_inputs_df

,ID,name,NDVI_minimum,NDVI_maximum,C4_fraction,carbon_uptake_efficiency,kn,peakVCmax_C3,peakVCmax_C4,ball_berry_slope_C3,...,KG_climate,CI,canopy_height_meters,COT,AOT,Ca,wind_speed_mps,vapor_gccm,ozone_cm,geometry
0,US-NC3,NC_Clearcut#3,0.408733,0.855693,0.077532,0.080000,0.410000,87.345433,51.040624,9.5,...,3,0.282353,20.642902,0,0,400,0,0,0.3,POINT (-76.656 35.799)
1,PE-QFR,Quistococha Forest Reserve,0.657359,0.826605,0.000549,0.060347,0.125033,41.364487,41.364487,9.5,...,1,0.254902,22.140021,0,0,400,0,0,0.3,POINT (-73.319 -3.8344)
2,US-Mi3,LTAR UCB (Upper Chesapeake Bay) Miscanthus 3,0.027910,0.855461,0.035045,0.080000,0.410000,119.435443,119.435443,7.5,...,4,0.286275,0.000000,0,0,400,0,0,0.3,POINT (-80.637 41.8222)
3,US-NC4,NC_AlligatorRiver,0.591358,0.869758,0.046219,0.080000,0.410000,64.720165,64.720165,9.5,...,3,0.207843,14.164827,0,0,400,0,0,0.3,POINT (-75.9038 35.7879)
4,CA-DB2,Delta Burns Bog 2,0.399712,0.675731,0.000356,0.080000,0.410000,109.986395,109.986395,9.5,...,3,0.266667,9.919029,0,0,400,0,0,0.3,POINT (-122.9951 49.119)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,US-xSL,"NEON North Sterling, CO (STER)",-0.025449,0.495206,0.340776,0.090000,0.710000,78.000000,40.000000,9.5,...,2,0.298039,0.000000,0,0,400,0,0,0.3,POINT (-103.0293 40.4619)
117,US-xWD,NEON Woodworth (WOOD),-0.041785,0.753863,0.032479,0.080000,0.410000,101.000000,37.000000,7.5,...,4,0.294118,0.000000,0,0,400,0,0,0.3,POINT (-99.2414 47.1282)
118,US-CS4,Central Sands Irrigated Agricultural Field,-0.003026,0.776740,0.092454,0.080000,0.410000,101.000000,37.000000,7.5,...,4,0.278431,0.000000,0,0,400,0,0,0.3,POINT (-89.5475 44.1597)
119,US-xAE,NEON Klemme Range Research Station (OAES),0.233503,0.554538,0.371127,0.090000,0.710000,78.000000,40.000000,9.5,...,3,0.301961,0.000000,0,0,400,0,0,0.3,POINT (-99.0588 35.4106)
120,US-GLE,GLEES,0.083431,0.708367,0.001423,0.088097,0.652918,137.813997,55.221827,7.5,...,4,0.200000,15.028475,0,0,400,0,0,0.3,POINT (-106.2399 41.3665)

In [6]:
# merge static inputs with model inputs, ignoring duplicate columns from static_inputs_df
cols_to_use = [col for col in static_inputs_df.columns if col not in model_inputs_gdf.columns or col == 'ID']
model_inputs_gdf = model_inputs_gdf.merge(static_inputs_df[cols_to_use], on="ID", how="left")
model_inputs_gdf

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,ball_berry_intercept_C3,KG_climate,CI,canopy_height_meters,COT,AOT,Ca,wind_speed_mps,vapor_gccm,ozone_cm
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,0.005267,3,0.282353,20.642902,0,0,400,0,0,0.3
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,0.009882,4,0.286275,0.000000,0,0,400,0,0,0.3
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,0.009882,4,0.286275,0.000000,0,0,400,0,0,0.3
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,0.009882,4,0.286275,0.000000,0,0,400,0,0,0.3
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,0.009882,4,0.286275,0.000000,0,0,400,0,0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,0.015000,3,0.301961,0.000000,0,0,400,0,0,0.3
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,0.015000,3,0.301961,0.000000,0,0,400,0,0,0.3
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,0.015000,3,0.301961,0.000000,0,0,400,0,0,0.3
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,0.015000,3,0.301961,0.000000,0,0,400,0,0,0.3
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,0.015000,3,0.301961,0.000000,0,0,400,0,0,0.3

In [7]:
model_inputs_gdf.columns

Index(['Unnamed: 0', 'ID', 'vegetation', 'climate', 'STICinst', 'BESSinst',
       'MOD16inst', 'PTJPLSMinst', 'ETinst', 'ETinstUncertainty', 'PET', 'Rn',
       'ESI', 'RH', 'Ta', 'LST', 'SM', 'NDVI', 'NDVI-UQ', 'albedo',
       'albedo-UQ', 'LST_err', 'view_zenith', 'Rg', 'EmisWB', 'time_utc',
       'solar_time', 'solar_hour', 'local_time', 'LE', 'LE_filt', 'LEcorr25',
       'LEcorr50', 'LEcorr75', 'LEcorr_ann', 'H_filt', 'Hcorr25', 'Hcorr50',
       'Hcorr75', 'Hcorr_ann', 'NETRAD_filt', 'G_filt', 'SM_surf', 'SM_rz',
       'AirTempC', 'SW_IN', 'RH_percentage', 'ESIrn_STIC', 'ESIrn_PTJPLSM',
       'ESIrn_MOD16', 'ESIrn_BESS', 'ESIrn_Unc_ECO', 'ESIrn_LEcorr50', 'JET',
       'eco_time_utc', 'Site Name', 'Date-Time', 'Site ID', 'Name', 'Lat',
       'Long', 'Elev', 'Clim', 'Veg', 'MAT', 'MAP', 'StartDate', 'EndDate',
       'LE_count', 'closure_ratio', 'geometry', 'time_UTC', 'ST_K', 'ST_C',
       'Ta_C', 'SWin_Wm2', 'emissivity', 'elevation_km', 'name',
       'NDVI_minimum', 'NDVI_maximum', 'C4_fraction',
       'carbon_uptake_efficiency', 'kn', 'peakVCmax_C3', 'peakVCmax_C4',
       'ball_berry_slope_C3', 'ball_berry_slope_C4', 'ball_berry_intercept_C3',
       'KG_climate', 'CI', 'canopy_height_meters', 'COT', 'AOT', 'Ca',
       'wind_speed_mps', 'vapor_gccm', 'ozone_cm'],
      dtype='object')

In [8]:
results = process_BESS_table(model_inputs_gdf)
results

[2025-09-09 16:54:04 INFO] started extracting geometry from PT-JPL-SM input table
[2025-09-09 16:54:04 INFO] completed extracting geometry from PT-JPL-SM input table
[2025-09-09 16:54:04 INFO] started extracting time from PT-JPL-SM input table
[2025-09-09 16:54:04 INFO] completed extracting time from PT-JPL-SM input table
[2025-09-09 16:54:04 INFO] GEOS-5 FP working directory: /Users/gregoryhalverson/data/GEOS5FP
[2025-09-09 16:54:04 INFO] GEOS-5 FP download directory: ~/data/GEOS5FP
[2025-09-09 16:54:04 INFO] variable elevation_km min: 0.001 mean: 0.993 max: 3.504 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Ta_C min: -14.605 mean: 22.322 max: 39.710 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable RH min: 0.273 mean: 0.427 max: 0.984 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable NDVI_minimum min: -0.033 mean: 0.174 max: 0.591 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable NDVI_maximum min: 0.314 mean: 0.628 max: 0.918 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable C4_fraction min: 0.000 mean: 0.296 max: 0.939 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable carbon_uptake_efficiency min: 0.080 mean: 0.083 max: 0.090 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable kn min: 0.410 mean: 0.514 max: 0.710 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable peakVCmax_C3 min: 52.821 mean: 88.903 max: 140.723 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable peakVCmax_C4 min: 37.000 mean: 65.191 max: 120.000 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable ball_berry_slope_C3 min: 7.500 mean: 8.698 max: 9.500 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable ball_berry_slope_C4 min: 4.100 mean: 5.177 max: 5.800 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable ball_berry_intercept_C3 min: 0.005 mean: 0.009 max: 0.015 nan: 0.00% (nan)
[2025-09-09 16:54:04 WARNING] Variable 'Rg' is None.
[2025-09-09 16:54:04 WARNING] Variable 'VISdiff' is None.
[2025-09-09 16:54:04 WARNING] Variable 'VISdir' is None.
[2025-09-09 16:54:04 WARNING] Variable 'NIRdiff' is None.
[2025-09-09 16:54:04 WARNING] Variable 'NIRdir' is None.
[2025-09-09 16:54:04 WARNING] Variable 'UV' is None.
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step
[2025-09-09 16:54:04 INFO] variable RVIS min: 0.015 mean: 0.109 max: 0.617 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable RNIR min: 0.015 mean: 0.109 max: 0.617 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable PARDir min: 111.324 mean: 305.792 max: 491.893 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable KG_climate (int64) with [1 2 3 4 5] unique values
[2025-09-09 16:54:04 INFO] * 1: 3
[2025-09-09 16:54:04 INFO] * 2: 473
[2025-09-09 16:54:04 INFO] * 3: 172
[2025-09-09 16:54:04 INFO] * 4: 413
[2025-09-09 16:54:04 INFO] * 5: 4
[2025-09-09 16:54:04 INFO] variable canopy_height_meters min: 0.000 mean: 6.044 max: 30.192 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Ca (float64) with [400.] unique values
[2025-09-09 16:54:04 INFO] * 400.0: 1065
[2025-09-09 16:54:04 INFO] variable wind_speed_mps (float64) with [7.4] unique values
[2025-09-09 16:54:04 INFO] * 7.4: 1065
[2025-09-09 16:54:04 INFO] variable Ps_Pa min: 64923.167 mean: 90420.237 max: 101313.196 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable VPD_Pa min: 9.430 mean: 1742.970 max: 4717.745 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable RH min: 0.273 mean: 0.426 max: 0.985 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable desTa min: 16.249 mean: 176.854 max: 387.676 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable ddesTa min: 1.197 mean: 9.169 max: 17.906 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable gamma min: 42.603 mean: 60.201 max: 68.164 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Cp min: 1005.693 mean: 1012.855 max: 1022.896 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable rhoa min: 0.776 mean: 1.067 max: 1.314 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable epsa min: 0.658 mean: 0.769 max: 0.873 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable R min: 6.213 mean: 24.217 max: 32.659 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rc min: 6.213 mean: 24.217 max: 32.659 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rs min: 3.107 mean: 12.109 max: 16.330 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable SFd min: 0.020 mean: 0.051 max: 0.083 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable SFd2 min: 0.157 mean: 0.331 max: 1.126 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable DL min: 7.316 mean: 11.455 max: 14.086 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Ra min: 409.312 mean: 901.634 max: 1276.344 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable fStress min: 0.007 mean: 0.295 max: 1.000 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable VCmax_C3_sunlit min: 1.804 mean: 39.242 max: 159.939 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable VCmax_C4_sunlit min: 1.438 mean: 30.612 max: 148.721 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable VCmax_C3_shaded min: 0.060 mean: 36.813 max: 264.371 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable VCmax_C4_shaded min: 0.060 mean: 31.494 max: 264.371 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable PARDiff min: 4.098 mean: 23.856 max: 38.928 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable PARDir min: 111.324 mean: 305.792 max: 491.893 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable NIRDiff min: 0.000 mean: 1.502 max: 9.685 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable NIRDir min: 157.569 mean: 392.475 max: 605.189 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable UV min: 14.987 mean: 45.044 max: 78.000 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable SZA min: 8.815 mean: 44.939 max: 72.288 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable LAI min: 0.076 mean: 1.285 max: 4.516 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable CI min: 0.184 mean: 0.278 max: 1.000 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable albedo_visible min: 0.015 mean: 0.109 max: 0.617 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable albedo_NIR min: 0.015 mean: 0.109 max: 0.617 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable kb min: 0.506 mean: 0.787 max: 1.643 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable kk_Pb min: 0.465 mean: 0.724 max: 1.512 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable kk_Nb min: 0.212 mean: 0.329 max: 0.688 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable kk_Nd (float64) with [0.1464155] unique values
[2025-09-09 16:54:04 INFO] * 0.14641550464346323: 1
[2025-09-09 16:54:04 INFO] variable fSun min: 0.118 mean: 0.240 max: 0.580 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable L_CI min: 0.021 mean: 0.374 max: 3.967 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable exp_kk_Pd_L_CI min: 0.057 mean: 0.795 max: 0.985 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable exp_kk_Nd_L_CI min: 0.559 mean: 0.949 max: 0.997 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PDn min: 3.366 mean: 56.575 max: 337.975 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PbSunDn min: 3.667 mean: 51.194 max: 300.849 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PdSunDn min: 0.174 mean: 3.678 max: 14.320 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PsSunDn min: 0.000 mean: 1.303 max: 14.898 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PSunDn min: 3.974 mean: 56.175 max: 317.433 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PShDn min: 0.000 mean: 1.165 max: 24.990 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable I_PSoil min: 3.323 mean: 236.525 max: 418.120 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable APAR_Soil min: 2.825 mean: 201.046 max: 355.402 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PSunUp min: 0.065 mean: 29.335 max: 60.323 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_PShUp min: 0.377 mean: 6.144 max: 21.583 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable APAR_Sun min: 24.109 mean: 85.510 max: 317.934 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable APAR_Sh min: 0.377 mean: 7.309 max: 33.773 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_NSunDn min: 1.817 mean: 29.846 max: 163.078 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_NShDn min: 0.008 mean: 4.626 max: 108.532 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable I_NSoil min: 51.784 mean: 316.871 max: 530.806 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable ANIR_Soil min: 36.249 mean: 221.810 max: 371.564 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_NSunUp min: 8.884 mean: 90.758 max: 153.486 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable Q_NShUp min: 0.206 mean: 4.303 max: 24.887 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable ANIR_Sun min: 47.061 mean: 120.604 max: 203.977 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable ANIR_Sh min: 0.213 mean: 8.929 max: 130.415 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable G min: 0.791 mean: 56.293 max: 99.512 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable sunlit_fraction min: 0.118 mean: 0.240 max: 0.580 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable APAR_sunlit min: 109.936 mean: 389.925 max: 1449.779 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable APAR_shaded min: 1.718 mean: 33.330 max: 154.003 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable ASW_sunlit min: 75.260 mean: 206.407 max: 516.332 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable ASW_shaded min: 0.722 mean: 17.210 max: 163.527 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable ASW_soil min: 54.380 mean: 464.405 max: 790.805 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable G min: 0.791 mean: 56.293 max: 99.512 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable GPP_C3 min: 0.000 mean: 8.884 max: 40.000 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable LE_C3 min: 0.000 mean: 117.583 max: 446.547 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable LE_soil_C3 min: 0.000 mean: 57.659 max: 253.737 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable LE_canopy_C3 min: 0.000 mean: 59.924 max: 381.385 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rn_C3 min: 0.000 mean: 498.559 max: 1000.000 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rn_soil_C3 min: 0.000 mean: 370.238 max: 698.149 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rn_canopy_C3 min: 0.000 mean: 128.363 max: 579.672 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable GPP_C4 min: 0.000 mean: 13.167 max: 50.000 nan: 0.19% (nan)
[2025-09-09 16:54:04 INFO] variable LE_C4 min: 0.000 mean: 119.701 max: 491.568 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable LE_soil_C4 min: 0.000 mean: 57.659 max: 253.737 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable LE_canopy_C4 min: 0.000 mean: 62.042 max: 443.605 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rn_C4 min: 0.000 mean: 498.559 max: 1000.000 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rn_soil_C4 min: 0.000 mean: 370.238 max: 698.149 nan: 0.00% (nan)
[2025-09-09 16:54:04 INFO] variable Rn_canopy_C4 min: 0.000 mean: 128.363 max: 579.672 nan: 0.00% (nan)

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,wind_speed_mps,vapor_gccm,ozone_cm,GPP,GPP_daily,Rn_soil,Rn_canopy,LE_soil,LE_canopy,G
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,0,0,0.3,16.306166,5.963702,343.088141,200.486306,69.342528,184.004129,37.045927
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,0,0,0.3,21.081704,8.623039,568.929428,176.618973,100.628336,125.136978,75.785976
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,0,0,0.3,19.984935,8.120491,595.207535,201.872465,210.893323,135.914517,77.675719
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,0,0,0.3,24.216487,10.357271,539.752171,195.049305,207.202548,129.500884,69.717555
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,0,0,0.3,21.872922,10.242349,441.941830,158.185783,140.032444,119.645512,57.794590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,0,0,0.3,0.492826,0.193133,165.684047,69.659646,41.487784,5.193484,29.244793
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,0,0,0.3,1.259612,0.882347,190.262323,75.928297,31.172926,11.745809,32.896598
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,0,0,0.3,3.360783,2.404805,266.716370,138.943197,6.239409,41.129234,35.811898
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,0,0,0.3,1.986428,1.197719,247.995207,66.902355,48.996907,10.137635,44.868324
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,0,0,0.3,0.879202,0.324015,512.595813,109.181784,26.306624,14.176772,84.415203

In [9]:
model_inputs_gdf.to_csv(generated_input_table_filename, index=False)

In [10]:
results.to_csv(generated_output_table_filename, index=False)